server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LvanLiang/springcloud-netflix-itoken.git
          search-paths: /itoken-config-respo/respo/*
          username: your account
          password: your password

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: config-server #自定义服务名称信息
    prefer-ip-address: true  #访问路径可以显示IP地址