server:
  port: 8888

spring:
  application:
    name: itoken-config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.3.128:8877/itoken/itoken-config.git
          search-paths: /respo/*
          username: liang
          password: root123,.
  boot:
    admin:
      client:
        url: http://192.168.3.129:8084
  zipkin:
    base-url: http://192.168.3.129:9411

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.3.129:8761/eureka/,http://192.168.3.129:8861/eureka/,http://192.168.3.129:8961/eureka/
  instance:
    instance-id: itoken-config #自定义服务名称信息
    prefer-ip-address: true  #访问路径可以显示IP地址

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info