stages:
  - build
  - push
  - run
  - clean

build:
  stage: build
  script:
    - mvn clean package
    - cp target/itoken-eureka-0.0.1-SNAPSHOT.jar docker
    - cd docker
    - docker build -t 192.168.3.129:5000/itoken-eureka .

push:
  stage: push
  script:
    - docker push 192.168.3.129:5000/itoken-eureka

run:
  stage: run
  script:
    - cd docker
    - docker-compose down
    - docker-compose up -d

clean:
  stage: clean
  script:
    - docker rmi $(docker images -q -f dangling=true)