spring:
  cloud:
    config:
      uri: http://192.168.3.129:8888
      name: itoken-service-admin,itoken-client-eureka, itoken-client-zipkin, itoken-client-admin
      label: master
      profile: prod